### ISSUE TITLE
Page still reloads after removing the plugin

### ISSUE THREAD

**Issue by jwald1** [ElMassimo/vite-plugin-full-reload#2]
I've removed the plugin from 'vite.config.ts' but Vite is still reloading the page. My setup was to reload on changes to 'views', 'components', and 'routes.rb'. My current config is:

```javascript
import { defineConfig } from "vite"
import RubyPlugin from "vite-plugin-ruby"
import StimulusHMR from "vite-plugin-stimulus-hmr"
import yaml from "@rollup/plugin-yaml"

export default defineConfig({
  build: {
    sourcemap: false,
  },
  plugins: [yaml(), RubyPlugin(), StimulusHMR()],
})
```

I restarted my machine and reinstalled Vite + plugins, but no luck.

Could anyone help with that? Thank you

**Comment by ElMassimo** [comment]
The plugin can't be the cause of the reload if it's not in the config.

Please [join the Vite.js Discord](https://discord.com/invite/4cmKdMfpU5) and drop a message in the `#dev-server` channel.

It will be helpful if you can share a minimal repo where you are experiencing the problem, and if you mention simple steps, such as:

> When I modify _the example.js file_, Vite performs a full page reload

**Comment by mtomov** [comment]
I have the same issue, and I tracked it down to those lines here:

https://github.com/vitejs/vite/blob/f402cd278c861e6351b27966d4f98bbb8bc34673/packages/vite/src/node/server/hmr.ts#L181-L190

which were caused by a Tailwind CSS import. If I remove the css import from the entrypoint JS file, then the full page refresh doesn't happen.

No clue if fixable / intended behaviour.

**Comment by 4ndv** [comment]
> I have the same issue, and I tracked it down to those lines here:
> 
> https://github.com/vitejs/vite/blob/f402cd278c861e6351b27966d4f98bbb8bc34673/packages/vite/src/node/server/hmr.ts#L181-L190
> 
> which were caused by a Tailwind CSS import. If I remove the css import from the entrypoint JS file, then the full page refresh doesn't happen.
> 
> No clue if fixable / intended behaviour.

Can confirm, including path to the tailwind's `content` config option causes page reload when any such file is changed. Maybe related to Tailwind's JIT?
