### ISSUE TITLE
Full Reload not working in Windows using `\\` paths separator

### ISSUE THREAD

**Issue by guasam** [ElMassimo/vite-plugin-full-reload#6]
Full Reload not working in `Windows` environment having paths as `app\\views\\**`

Making following changes to source seems to be working: 

**Changes**
```js
const files = Array.from(paths).map(path => resolve(root, path).replace(/\\/g, '/')) 
```

**Original**
https://github.com/ElMassimo/vite-plugin-full-reload/blob/0899c1355a364a66e817169c1f01711823b85b51/src/index.ts#L49

**Comment by timacdonald** [comment]
@guasam could you please provide your `vite.config.js` file?

@ElMassimo I know that Vite exposes a path normalisation function (`normalizePath`) that we might wanna lean on, just to not bring in another dep for you?

**Comment by timacdonald** [comment]
ahh, looks like that might only be exported in Vite 3?

Is your general plan to continue to support both v2 and v3 moving forward?

**Comment by guasam** [comment]
@timacdonald Following `vite.config.js` was used to setup frontend with Vite & Laravel in Windows 11 environment.

```js
import { defineConfig, splitVendorChunkPlugin, loadEnv } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [
    laravel({
      input: ['resources/scripts/core.js', 'resources/styles/core.css'],
      ssr: 'resources/scripts/ssr.js',
      refresh: true,
    }),
    vue(),
    splitVendorChunkPlugin(),
  ],
  server: {
    host: loadEnv('', process.cwd()).VITE_SERVER_HOST,
  },
});

``

**Comment by timacdonald** [comment]
Hoping to fix this over here: https://github.com/ElMassimo/vite-plugin-full-reload/pull/7

**Comment by ElMassimo** [comment]
Thanks for the fix Tim!

Added `vite` as a `peerDependency` and released [`vite-plugin-full-reload@1.0.2`](https://github.com/ElMassimo/vite-plugin-full-reload/blob/main/CHANGELOG.md#102-2022-07-21).

@guasam Let us know if the problem persists, as we haven't tested on Windows.

**Comment by timacdonald** [comment]
Woo!

**Comment by timacdonald** [comment]
@ElMassimo just yolo'd the release 🤣🔥

**Comment by ElMassimo** [comment]
There should be a [GitHub achievement](https://github.com/ElMassimo?tab=achievements) for that 😄

**Comment by timacdonald** [comment]
🏆🏆🏆
